### ISSUE TITLE
nhooyr.io/cli cannot be imported

### ISSUE THREAD

**Issue by rogpeppe** [nhooyr/cli#5]
I can't import this package. It seems that the vanity import path isn't valid.

```
% go get nhooyr.io/cli
go get nhooyr.io/cli: unrecognized import path "nhooyr.io/cli": reading https://nhooyr.io/cli?go-get=1: 404 Not Found
```

This also means it doesn't show up on pkg.go.dev.

**Comment by nhooyr** [comment]
Nice catch!

This library was more of an experiment for me and not something I would use. I'll remove the vanity import so that it still works though. And I'll add a note in the README regarding its experimental status.

**Comment by rogpeppe** [comment]
Thanks for the update :) FWIW I've been looking for the "right" minimal CLI API for a while now... haven't found it yet. But something like this might be getting towards it.

**Comment by nhooyr** [comment]
> FWIW I've been looking for the "right" minimal CLI API for a while now... haven't found it yet.

Same. Hard to believe how bloated the popular CLI libraries are.

> But something like this might be getting towards it.

I agree there's definitely value in cli's design. I can't quite remember why I wasn't happy enough with it. It's on my TODO to take another stab at it, clean it up and write some nice docs.
